### ISSUE TITLE
Mark-1: GLIBCXX_3.4.21 not found

### ISSUE THREAD

**Issue by domcross** [MycroftAI/plugin-wake-word-precise-lite#2]
**Describe the bug**
Fails on Mark-I (mycroft-core 21.2.1) with 

```
2021-10-25 14:16:29.974 | ERROR    |   905 | mycroft.client.speech.hotword_factory:initialize:529 | Could not create hotword. Falling back to default.
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/mycroft/client/speech/hotword_factory.py", line 510, in initialize
    clazz = load_wake_word_plugin(module)
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/mycroft/client/speech/hotword_factory.py", line 482, in load_wake_word_plugin
    return load_plugin('mycroft.plugin.wake_word', module_name)
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/mycroft/util/plugins.py", line 48, in load_plugin
    plugins = find_plugins(plug_type)
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/mycroft/util/plugins.py", line 34, in find_plugins
    in pkg_resources.iter_entry_points(plug_type)
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/mycroft/util/plugins.py", line 33, in <dictcomp>
    for entry_point
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/hotword_precise_lite/__init__.py", line 15, in <module>
    from .mycroft_hotword import TFLiteHotWord
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/hotword_precise_lite/mycroft_hotword.py", line 6, in <module>
    from .network_runner import ReadWriteStream, Listener, Engine
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/hotword_precise_lite/network_runner.py", line 16, in <module>
    import tflite_runtime.interpreter as tflite
  File "/opt/venvs/mycroft-core/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 41, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /opt/venvs/mycroft-core/lib/python3.7/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.cpython-37m-arm-linux-gnueabihf.so)
```

**To Reproduce**
1. clone repository and `cd`into it
2. create/increase swap to 1GB (for scipy build)
3. `sudo mycroft-pip install .`
4. configure "hotword" in `mycroft.conf`
5. reboot/restart Mycroft and look into voice.log

**Environment (please complete the following information):**
 - Device type: Mark 1
 - OS: Raspbian/Debian Jessie
 - Mycroft-core version: 21.2.1

**Comment by krisgesling** [comment]
Thanks for giving it a go Dominik. I hadn't tried it on a Mark 1 at all. 

It's not something that I think we'll have time to prioritize, but interested if someone does find a fix.

**Comment by domcross** [comment]
Upgrading GLIBCXX (by installing libstdc++.so from Debian Stretch distro) leads to next error - GLIBC version does not match. 
As GLIBC is deeply linked into system I do not see a chance to get this running on Mark-I / Debian Jessie.
